version: '2'
services:
  db:
    container_name: collector_db_container
    image: postgres:9.5
    volumes:
      - collector_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=collectordb
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
  admin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@test.com
      - PGADMIN_DEFAULT_PASSWORD=test
    ports:
      - 80:80

volumes:
  collector_db: {}